### ISSUE TITLE
Issue after upgrading

### ISSUE THREAD

**Issue by williamtwomey** [gtmanfred/hammercloud#5]
After performing a pip install --upgrade hammercloud (and putting a config.yaml into place) I'm seeing the following error:

stevedore.exception.NoMatches: No 'hammercloud.rackspace' driver found, looking for 'Server'

Hammercloud had previously been installed and functional.

Just wondering if this is an issue with the upgrade process or if anyone has suggestions.

Thanks!

**Comment by KaiSforza** [comment]
If you're setting the plugin to `rackspace` you also need the plugin from the internal rackspace github.

**Comment by gtmanfred** [comment]
You will need to contact bill giokas if you still need help setting up the rackspace plugin for hammercloud.
